const path = require('path');
const { readdirSync, writeFile } = require('fs');

const cwd = process.cwd();
const inputFolder = path.resolve(cwd, 'src/Icon/icon-asset');
const resultFolder = path.resolve(cwd, 'src/Icon');

let content = '';
let exportResult = '';

content = '/* Generated by `yarn icon-gen` command */\n';
content += '/* eslint-disable */\n'; // disable eslint for the file

readdirSync(inputFolder).forEach(file => {
  const filename = path.basename(file, path.extname(file));
  exportResult += `\t'${filename}': () =>  import('./icon-asset/${filename}'),\n`;
});

content += `\n\nexport default {\n${exportResult}}`;

writeFile(`${resultFolder}/generated-icons.tsx`, content, 'utf-8', err => {
  if (err) {
    throw err;
  }
  console.log('Generate icons done!');
});
