const path = require('path');
const { readdirSync, writeFile } = require('fs');

const cwd = process.cwd();
const svgFolder = path.resolve(cwd, 'src/components/Spot/svg');
const resultFolder = path.resolve(cwd, 'src/components/Spot');

let content = '';
let exportResult = '';

content = '/* Generated by `yarn icon-gen` command */\n';
content += '/* eslint-disable */\n'; // disable eslint for the file

readdirSync(svgFolder).forEach(file => {
  const filename = path.basename(file, path.extname(file));
  exportResult += `\t'${filename}': () =>  import('./svg/${filename}'),\n`;
});

content += `\n\nexport default {\n${exportResult}}`;

writeFile(`${resultFolder}/generated-spots.tsx`, content, 'utf-8', err => {
  if (err) {
    throw err;
  }
  console.log('Generate spots done!');
});
